# Generated by Django 2.1.1 on 2018-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastfmArtistProcessQueueItem',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_fm_artist_url', models.CharField(max_length=200)),
                ('processed', models.BooleanField()),
                ('processed_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastfmUserProcessQueueItem',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_fm_user_url', models.CharField(max_length=200)),
                ('processed', models.BooleanField()),
                ('processed_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('spotify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('spotify_url', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('last_fm_track_url', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('last_fm_artist_url', models.CharField(max_length=200)),
                ('manually_mapped', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
